name: Try importing the latest One Piece Chapter

on:
  # schedule:
  #   # Every tenth minute from Thursday through Monday
  #   - cron: "*/10 * * * 4/6"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: node --loader ts-node/esm packages/demo/src/main.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
